/**
 * One-time / on-update Remotion Lambda deploy script.
 *
 * What it does (idempotent — safe to re-run):
 *   1. Ensures an S3 bucket exists in the target region (Remotion needs one
 *      for both the bundled site and the rendered output files).
 *   2. Deploys the Lambda function with sized resources for our composition.
 *      Re-running upgrades the function in place if the @remotion/lambda
 *      package version changed.
 *   3. Bundles the remotion/ folder and uploads it to S3 as the "site".
 *      Re-running with the same site name overwrites the existing bundle.
 *   4. Writes the resulting serve URL into the admin_settings table
 *      (key=`remotion_serve_url`) so the API routes can pick it up at
 *      runtime without needing a Vercel env var push.
 *   5. Prints the function name so you can paste it into REMOTION_LAMBDA_FUNCTION_NAME
 *      in .env.local and Vercel.
 *
 * REQUIREMENTS:
 *   - .env.local must contain REMOTION_AWS_ACCESS_KEY_ID, REMOTION_AWS_SECRET_ACCESS_KEY,
 *     REMOTION_AWS_REGION, NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY.
 *   - The IAM user must have the policies generated by:
 *       npx remotion lambda policies user
 *       npx remotion lambda policies role
 *
 * RUN: npm run remotion:deploy
 *
 * COST WARNING: Running this for the first time creates real AWS resources
 * (Lambda function ~free at idle, S3 bucket ~free at idle, CloudWatch Log
 * Group ~free at idle). Renders cost ~$0.02-0.04 per ~15s 1080p video.
 */

import {
  deployFunction,
  deploySite,
  getOrCreateBucket,
} from "@remotion/lambda";
import { createClient } from "@supabase/supabase-js";
import * as fs from "fs";
import * as path from "path";

// Load env from .env.local (same pattern as the other scripts in this folder)
const envPath = path.resolve(process.cwd(), ".env.local");
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, "utf-8").split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq === -1) continue;
    const k = t.slice(0, eq).trim();
    const v = t.slice(eq + 1).trim();
    if (!process.env[k]) process.env[k] = v;
  }
}

// Remotion Lambda picks up AWS credentials from the standard env var names,
// but we use the REMOTION_-prefixed ones in this project so they can't be
// confused with other AWS clients in the future. Bridge them here.
if (process.env.REMOTION_AWS_ACCESS_KEY_ID && !process.env.AWS_ACCESS_KEY_ID) {
  process.env.AWS_ACCESS_KEY_ID = process.env.REMOTION_AWS_ACCESS_KEY_ID;
}
if (
  process.env.REMOTION_AWS_SECRET_ACCESS_KEY &&
  !process.env.AWS_SECRET_ACCESS_KEY
) {
  process.env.AWS_SECRET_ACCESS_KEY = process.env.REMOTION_AWS_SECRET_ACCESS_KEY;
}

const REGION =
  (process.env.REMOTION_AWS_REGION as
    | "us-east-1"
    | "us-east-2"
    | "us-west-1"
    | "us-west-2") ?? "us-east-1";
const SITE_NAME = "landscaip-finalize";
const ENTRY_POINT = path.resolve(process.cwd(), "remotion/index.ts");

// Lambda sizing: 3GB memory gives 2 vCPUs which renders comfortably for our
// short composition. Disk size accommodates the source veo + render output.
const LAMBDA_MEMORY_MB = 3008;
const LAMBDA_DISK_MB = 10240;
const LAMBDA_TIMEOUT_S = 240;

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!process.env.AWS_ACCESS_KEY_ID || !process.env.AWS_SECRET_ACCESS_KEY) {
  console.error(
    "Missing AWS credentials. Set REMOTION_AWS_ACCESS_KEY_ID and REMOTION_AWS_SECRET_ACCESS_KEY in .env.local."
  );
  process.exit(1);
}

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error(
    "Missing Supabase env vars. Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local."
  );
  process.exit(1);
}

async function main() {
  console.log(`\n=== Remotion Lambda deploy → ${REGION} ===\n`);

  // 1. Bucket
  console.log("[1/4] Ensuring S3 bucket exists...");
  const { bucketName } = await getOrCreateBucket({ region: REGION });
  console.log(`      bucket: ${bucketName}\n`);

  // 2. Function
  console.log("[2/4] Deploying Lambda function...");
  const { functionName, alreadyExisted } = await deployFunction({
    region: REGION,
    timeoutInSeconds: LAMBDA_TIMEOUT_S,
    memorySizeInMb: LAMBDA_MEMORY_MB,
    diskSizeInMb: LAMBDA_DISK_MB,
    createCloudWatchLogGroup: true,
  });
  console.log(
    `      function: ${functionName} ${alreadyExisted ? "(already existed)" : "(newly created)"}\n`
  );

  // 3. Site bundle
  console.log("[3/4] Bundling and uploading site...");
  const { serveUrl } = await deploySite({
    bucketName,
    entryPoint: ENTRY_POINT,
    region: REGION,
    siteName: SITE_NAME,
    options: {
      onBundleProgress: (p) => {
        process.stdout.write(`\r      bundling: ${p}%`);
      },
      onUploadProgress: ({ filesUploaded, totalFiles }) => {
        process.stdout.write(
          `\r      uploading: ${filesUploaded}/${totalFiles} files`
        );
      },
    },
  });
  process.stdout.write("\n");
  console.log(`      serveUrl: ${serveUrl}\n`);

  // 4. Persist serveUrl in admin_settings
  console.log("[4/4] Writing serveUrl to admin_settings table...");
  const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);
  const { error: upsertErr } = await supabase
    .from("admin_settings")
    .upsert(
      {
        key: "remotion_serve_url",
        value: serveUrl,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "key" }
    );
  if (upsertErr) {
    console.error(
      "      WARNING: failed to write serveUrl to admin_settings:",
      upsertErr.message
    );
    console.error(
      "      You'll need to set it manually before the finalize API can render."
    );
  } else {
    console.log("      saved.\n");
  }

  console.log("=== Deploy complete ===\n");
  console.log("Next steps:");
  console.log(
    `  1. Add REMOTION_LAMBDA_FUNCTION_NAME=${functionName} to .env.local AND Vercel.`
  );
  console.log(
    "  2. If you haven't yet, generate REMOTION_WEBHOOK_SECRET via:  openssl rand -hex 32"
  );
  console.log(
    "     and add it to .env.local AND Vercel (Lambda will sign webhook callbacks with it)."
  );
  console.log(
    "  3. Verify the deploy by checking the AWS Lambda console for the function."
  );
  console.log(
    `  4. Re-run this script any time you change files in remotion/ — it's idempotent.`
  );
}

main().catch((err) => {
  console.error("\nDeploy failed:", err);
  process.exit(1);
});
